## YAML Template.
topics: 
    - /odom
    - /cmd_vel
    - /navigation/map

nodes:
    move_base_flex:
        - /cmd_vel 
    odom:
        - /odom
    navigation_stack:
        - /odom
        - /cmd_vel
    navigation_map_server:
        - /navigation/map