## YAML Template.
topics: 
    - /odom
    - /cmd_vel
    - /navigation/map
    - /imu/data_raw_transformed
    - /imu/data_raw

nodes:
    move_base_flex:
        - /cmd_vel 
    odom:
        - /odom
    navigation_stack:
        - /odom
        - /cmd_vel
    navigation_map_server:
        - /navigation/map
    robot_stopped:
        - /cmd_vel
        - /navigation/map
    cartographer:
        - /imu/data_raw_transformed
        - /odom
    imu_manager:
        - /imu/data_raw