## YAML Template.
topics: 
    - /odom
    - /cmd_vel
    #- /navigation/map
    - /imu/data_raw_transformed
    - /imu/data_raw
    - /wheel_angles

nodes:
    stopped_robot:
        - /cmd_vel 
    odometry_publisher:
        - /odom
    navigation_stack:
        - /odom
        - /cmd_vel
    cartographer:
        - /imu/data_raw_transformed
        - /odom
    imu_manager:
        - /imu/data_raw
        - /imu/data_raw_transformed
    imu_sensor:
        - /imu/data_raw
    inertial_noise:
        - /imu/data_raw
        - /cmd_vel
    wheels:
        - /wheel_angles
    navigation_map_server:
        - /navigation/map
 