local_costmap:
  global_frame: /map                    # default : /map
  inflation_radius: 0.6                 # default : 0.46
  robot_base_frame: base_link           # default : base_footprint
  update_frequency: 2.0                 # default : 2.0
  publish_frequency: 2.0                # default : 2.0
  static_map: false                     # default : false
  rolling_window: true                  # default : True
  width: 3.0                            # default : 2.5
  height: 3.0                           # default : 2.5
  resolution: 0.05                      # default : 0.02
  footprint_padding: 0.01               # default : 0.01
  #plugins:
  #  - {name: simple, type: "simple_costmap_layer::SimpleLayer"}
  plugins:
      - {name: static_map, type: "costmap_2d::StaticLayer"}
      - {name: obstacles,  type: "costmap_2d::VoxelLayer"}
      - {name: inflater,   type: "costmap_2d::InflationLayer"}
